config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /en|zh-CN/ do
    root 'static_pages#home'
    get 'index' => 'static_pages#home'
    get 'about' => 'static_pages#about'
    get 'activities' => 'static_pages#activities'
    get 'services' => 'static_pages#services'
    get 'faq' => 'static_pages#faq'
    get 'disclaimer' => 'static_pages#disclaimer'
    get 'privacy' => 'static_pages#privacy'
    devise_for :users
    resources :users
    resources :news_links
  end

end

app/models/news_link.rb
class NewsLink < ActiveRecord::Base
  validates_presence_of :title, :message => "Title can't be blank!"
  validates_uniqueness_of :title, :message => "Title already exists!"
  validates_presence_of :link, :message => "Link can't be blank!"
  validate :valide_url

  self.per_page = 10

  def valide_url
    unless link =~ /\A#{URI::regexp(['http', 'https'])}\z/
      errors.add(:link, "Invalid URL!")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable,  and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
    :recoverable, :rememberable, :trackable, :validatable,
    :timeoutable

  self.per_page = 10

  def full_name
    [self.first_name, self.last_name].join(' ')
  end

  def full_name=(name)
    split = name.split(' ', 2)
    self.first_name = split.first
    self.last_name = split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale

  def default_url_options
    { locale: I18n.locale }
  end

  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

end

app/controllers/news_links_controller.rb
class NewsLinksController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @news_links = NewsLink.page(params[:page]).order(created_at: :desc)
  end

  def new
    @news_link = NewsLink.new
  end

  def create
    @news_link = NewsLink.create(news_link_params)
    if @news_link.save
      redirect_to news_links_path
    else
      render 'new'
    end
  end

  #def show
    #@news_link = NewsLink.find(params[:id])
    #respond_to do |format|
      #format.html
    #end
  #end

  def edit
    @news_link = NewsLink.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def update
    @news_link = NewsLink.find(params[:id])

    if @news_link.update(news_link_params)
      redirect_to news_links_path
    else
      render 'edit'
    end
  end


  def destroy
    @news_link = NewsLink.find(params[:id])
    @news_link.destroy

    redirect_to news_links_path
  end

  private
  # Using a private method to encapsulate the permissible parameters
  # is just a good pattern since you'll be able to reuse the same
  # permit list between create and update. Also, you can specialize
  # this method with per-user checking of permissible attributes.
  def news_link_params
    params.require(:news_link).permit(:title, :link)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @news_links = NewsLink.order(created_at: :desc).limit(10)
  end

  def about
  end

  def activities
  end

  def services
    @tables = Dir.glob("app/assets/files/*.docx")
  end

  def faq
  end

  def disclaimer
  end

  def privacy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  before_action :authenticate_user!
  before_action :has_permissioin , except: :index

  def index
    unless current_user.admin?
      flash[:notice] = "Must be admin!"
      redirect_to current_user
    end
    @users = User.paginate(page: params[:page]).order(created_at: :desc)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @user.destroy
    flash[:notice] = "User '#{@user.email}' deleted."
    redirect_to users_path
  end


  private
  def user_params
    params.require(:user).permit(:id, :full_name, :company)
  end

  def has_permissioin
    @user = User.find(params[:id])
    unless (@user and @user == current_user) or current_user.admin?
      flash[:notice] = "Must be admin!"
      redirect_to current_user
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/i18n_helper.rb
module I18nHelper
  def translate(key, options={})
    super(key, options.merge(raise: true))
  rescue I18n::MissingTranslationData
    key
  end
  alias :t :translate
end

app/helpers/news_links_helper.rb
module NewsLinksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
    <div class="container text-muted">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-3">
                <%= image_tag("logo.png", size: "160x70", alt: "HanSeBridge") %>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <h4><span class="fa fa-star"></span> Copyright</h4>
                <p>©2015 HanSeBridge org.</p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <h4><span class="fa fa-envelope"></span> Email:</h4>
                <p><a href="mailto:info@hansebridge.org">info@hansebridge.org</a></p>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3">
                <h4><span class="fa fa-heart"></span> Site developed by</h4>
                <%= link_to "Chuan Jin", "http://chuanjin.me/about"%>
            </div>
        </div>

        <div id="bottom">
            <ul>
                <li><%= link_to t("FAQ"), faq_path %></li>
                <li>•</li>
                <li><%= link_to t("Disclaimer"), disclaimer_path %> </li>
                <li>•</li>
                <li><%= link_to t("Privacy"), privacy_path %></li>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
<div id="header">

    <div class="lead text-center container">
        <h1>
            <div class="golden"> Hansebridge International Chamber of Commerce </div>
        </h1>
        <h1>
            <div class="golden"> 汉瑞金桥国际商会 </div>
        </h1>
    </div>

</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
    <% unless key.to_s == 'timedout' %>
        <div class="alert alert-<%= key %>">
            <a href="#" data-dismiss="alert" class="close">×</a>
            <ul>
                <li>
                    <%= value %>
                </li>
            </ul>
        </div>
    <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to index_path do %>
                        <i class="fa fa-home fa-1g icon_color"></i>
                        <span class="golden">
                            <%= t('Home') %>
                        </span>
                    <% end %>
                </li>
                <!--
                    <li>
                    <%= link_to activities_path do %>
                        <i class="fa fa-calendar fa-1g icon_color"></i>
                        <span class="golden">
                        <%= t('Activities') %>
                        </span>
                    <% end %>
                    </li>
                -->
                <li>
                    <%= link_to services_path do %>
                        <i class="fa fa-briefcase fa-1g icon_color"></i>
                        <span class="golden">
                            <%= t('Services') %>
                        </span>
                    <% end %>
                </li>
                <li>
                    <%= link_to about_path do %>
                        <i class="fa fa-group fa-1g icon_color"></i>
                        <span class="golden">
                            <%= t('About') %>
                        </span>
                    <% end %>
                </li>
                <li>
                    <%= link_to faq_path do %>
                        <i class="fa fa-question-circle fa-1g icon_color"></i>
                        <span class="golden">
                            <%= t('FAQ') %>
                        </span>
                    <% end %>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to image_tag("us.png"), locale: :en%>
                </li>
                <li>
                    <%= link_to image_tag("zh.png"), locale: :'zh-CN'%>
                </li>
                <% if user_signed_in? %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user fa-1g icon_color"></i><span class="golden"></span><b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <%= link_to current_user do %>
                                    <i class="fa fa-user fa-1g icon_color"></i>
                                    <span class="golden">
                                        <%= t('Profile') %>
                                    </span>
                                <% end %>
                            </li>
                            <li>
                                <%= link_to edit_user_registration_path do %>
                                    <i class="fa fa-key fa-1g icon_color"></i>
                                    <span class="golden">
                                        <%= t('Reset Password') %>
                                    </span>
                                <% end %>
                            </li>
                            <li>
                                <%= link_to news_links_path do %>
                                    <i class="fa fa-bullhorn fa-1g icon_color"></i>
                                    <span class="golden">
                                        <%= t('News') %>
                                    </span>
                                <% end %>
                            </li>
                            <% if current_user.admin?  %>
                                <li>
                                    <%= link_to users_path do %>
                                        <i class="fa fa-group fa-1g icon_color"></i>
                                        <span class="golden">
                                            <%= t('Users') %>
                                        </span>
                                    <% end %>
                                </li>
                            <% end %>
                            <li class="divider"></li>
                            <li>
                                <%= link_to destroy_user_session_path, method: :delete do %>
                                    <i class="fa fa-sign-out fa-1g icon_color"></i>
                                    <span class="golden">
                                        <%= t('Log Out') %>
                                    </span>
                                <% end %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li>
                        <%= link_to new_user_registration_path do %>
                            <i class="fa fa-user fa-1g icon_color"></i> 
                            <span class="golden">
                                <%= t('Sign up') %> 
                            </span>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to new_user_session_path do %>
                            <i class="fa fa-sign-in fa-1g icon_color"></i> 
                            <span class="golden">
                                <%= t('Sign in') %> 
                            </span>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div><!--/.nav-collapse -->
    </div><!--/.container -->
</div><!--/.navbar -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= t('HanSEbridge') %> | <%= yield(:title) %></title>

        <meta charset="UTF-8">
        <meta name="description" content="Hansebridge International Chamber of Commerce (汉瑞金桥国际商会) is a non profit organization. Focus on the connection between China and Sweden.">
        <meta name="keywords" content="Hansebridge, International Chamber of Commerce, 汉瑞金桥国际商会, 瑞典商会">
        <meta name="author" content="Chuan Jin">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <%= render 'layouts/shim' %>
    </head>
    <body id="body">
        <%= render 'layouts/nav' %>
        <%= render 'layouts/header' %>

        <%= render 'layouts/messages' %>
        <%= yield %>

        <%= render 'layouts/footer' %>  
    </body>
</html>


<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-42884687-7', 'auto');
ga('send', 'pageview');

</script>

app/views/news_links/edit.html.erb
<% @news_link.errors.each do |key, value|  %>
    <div class="alert alert-error %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <ul>
            <li>
                <%= value %>
            </li>
        </ul>
    </div>
<% end %>

<div class="divider"></div>

<div class="container">
    <div class="row vertical-offset-100">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="golden"><%= t('Update the news link') %></span></h3>
                </div>
                <div class="panel-body">
                    <%= form_for @news_link, url: {action: "update"} do |f| %>
                        <fieldset>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-header icon_color"></span></span>
                                    <%= f.text_field :title, placeholder: t('Title'), class:"form-control", autocomplete: "off" %>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-link icon_color"></span></span>
                                    <%= f.text_field :link, placeholder: t('Link'), class:"form-control", autocomplete: "off" %>
                                </div>
                            </div>
                            <input class="btn btn-lg btn-success btn-block" type="submit" value=<%= t('Submit') %> >
                        </fieldset>
                    <% end %>
                </div>
            </div>
        </div>
    </div>

    <div class="alert alert-warning" align="center">
        <%= link_to t("Back"), news_links_path , class: 'btn btn-sm btn-primary' %>
    </div>
</div>


<div class="divider"></div>

app/views/news_links/index.html.erb
<% provide(:title, t("News")) %>

<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="page-header text-center">
            <h1><i class="fa fa-bullhorn fa-1g icon_color"></i> <span class="golden"> <%= t('News')%></span> </h1>
        </div>

        <div class="col-sm-10 col-sm-offset-1">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th><%= t('Title') %></th>
                        <th><%= t('Created at') %></th>
                        <th><%= t('Updated at') %></th>
                        <th><%= t('Actions') %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @news_links.each do |news_link| %>
                        <tr>
                            <td> <%= link_to news_link.title, news_link.link %></td>
                            <td> <%= news_link.created_at %></td>
                            <td> <%= news_link.updated_at %></td>
                            <td>
                                <%= link_to t('Edit'), edit_news_link_path(news_link), :class => 'btn btn-warning' %>
                                <%= link_to t('Delete'), news_link_path(news_link), :method => :delete, data: {confirm: t("Are you sure?")}, :class => 'btn btn-mini btn-danger' %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <%= link_to t('New'), new_news_link_path, :class => 'btn btn-primary' %>
            <br/>
            <%= will_paginate %>
        </div>
    </div>
</div>


<div class="divider"></div>

app/views/news_links/new.html.erb
<% @news_link.errors.each do |key, value|  %>
    <div class="alert alert-error %>">
        <a href="#" data-dismiss="alert" class="close">×</a>
        <ul>
            <li>
                <%= value %>
            </li>
        </ul>
    </div>
<% end %>

<div class="divider"></div>

<div class="container">
    <div class="row vertical-offset-100">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="golden"><%= t('Create a new news link') %></span></h3>
                </div>
                <div class="panel-body">
                    <%= form_for @news_link, url: {action: "create"} do |f| %>
                        <fieldset>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-header icon_color"></span></span>
                                    <%= f.text_field :title, placeholder: t('Title'), class:"form-control", autocomplete: "off" %>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <span class="input-group-addon"><span class="fa fa-link icon_color"></span></span>
                                    <%= f.text_field :link, placeholder: t('Link'), class:"form-control", autocomplete: "off" %>
                                </div>
                            </div>
                            <input class="btn btn-lg btn-success btn-block" type="submit" value=<%= t('Submit') %> >
                        </fieldset>
                    <% end %>
                </div>
            </div>
        </div>
    </div>

    <div class="alert alert-warning" align="center">
        <%= link_to t("Back"), news_links_path , class: 'btn btn-sm btn-primary' %>
    </div>
</div>


<div class="divider"></div>

app/views/static_pages/_about_contents.en.html.erb
<h4>
The HanSeBridge International Chamber of Commerce is a non-profit and non-governmental

organization. The first council consists of distinguished scholars in Sweden, PhD supervisors, 

PhDs at famous Swedish universities, entrepreneurs from different fields, experts in financial 

industry as well as other industries.
</h4>

app/views/static_pages/_about_contents.zh-CN.html.erb
<h4>
本商会属非营利性民间自发组织。首届理事会是由瑞典知名大学学者、博士生导师、知名
高校博士、在读博士以及各行业具有影响力的企业家、经验丰富的金融行业和企业的专业人士组成。
</h4>

app/views/static_pages/_disclaimer_contents.en.html.erb
<% content_for :content_1 do %>
    The HanSeBridge International Chamber of Commerce (abbreviated as “the Chamber of Commerce” as follows) tries its best to provide true and effective information. However, those provided information is primitive and general, users cannot make request on the integrity of information. Although all the information is provided by careful selection and verification, the Chamber of Commerce takes no responsibility for the integrity and accuracy of the data.
<% end %>

<% content_for :content_2 do %>
    Paragraphs, pictures and other kinds of productions on our website noted with “From website...” are from external websites with the purpose of disseminating more information. Therefore, it does not mean that the Chamber of Commerce is supporting the viewpoints of those contents and thoughts.
<% end %>

<% content_for :content_3 do %>
    All contents published on this website, including but not limited to texts, images, audio-videos, logos, identities, advertisements, trademarks, web pages, software, programme, layout designs, column catalogs, taxonomy of contents and information provided are subjected to the Swedish copyright law (Upphovsrättslagen), the Swedish patent law (Patenträttslagen), the Swedish trademark law (Varumärkeslagen) and other international regulations.
<% end %>

<% content_for :content_4 do %>
    Without written authorization by the Chamber of Commerce, any agencies, persons should not use the information and services provided by us for commercial purpose. Additionally, it is not allowed to modify, reproduce, link, copy, publish, spread, sell parts of our products (information) and service. Any media, websites and commercial organizations should not utilize the services and contents provided by our website for commercial purpose. In addition, it is not allowed to distort the content/information provided by our website. The violators of legal liability shall be pursued in accordance with the law.
<% end %>

<% content_for :content_5 do %>
    Any media or websites cannot directly reproduce information from our website provided by other entity units, if necessary, one should contact directly with those entity units.
<% end %>

<% content_for :content_6 do %>
    If data or information provided in this website do not agree with the relevant paper-based documents, please refer to paper-based documents; if discrepancy exists in the documents between the English and the Chinese version, the Chinese version is given the highest priority.
<% end %>

app/views/static_pages/_disclaimer_contents.zh-CN.html.erb
<% content_for :content_1 do %>
    本商会尽可能为用户提供真实有效的信息。然而，本信息仅为初步提示，使用者不得对其完整性提出要求。即使所有材料已尽最大的谨慎提供、选择和校验，信息提供者对于信息的完整性以及内容的正确性不承担任何责任。
<% end %>

<% content_for :content_2 do %>
    凡本网注明“来源：某某网”的作品和文字以及图片，均转载自其它媒体，转载目的在于传递更多信息，并不代表本网赞同其观点和对其真实性负责。
<% end %>

<% content_for :content_3 do %>
    本网站所登载发布的一切内容，包括但不限于文字、图片、音像、图表、标志、标识、广告、商标、域名、软件、程序、版面设计、专栏目录与名称、内容分类标准以及为使用者提供的任何信息，均受《瑞典著作权法》、《瑞典商标法》、《瑞典专利法》等法律法规以及有关国际条约的保护，相应权利由网站业主单位及 / 或相关权利人享有。
<% end %>

<% content_for :content_4 do %>
    未经本网站业主单位书面授权许可，任何机构、个人不得对本网站提供的信息和服务内容作任何商业目的之使用，亦不得改动、转载、链接、复制、发行、传播、出售本站的部分或全部内容及服务，或将之在非本站所属的服务器上作镜像。任何媒体、互联网站和商业机构不得利用本网站提供的信息和服务内容进行商业性的转载，也不得歪曲和篡改本网站所发布的内容。否则，本网站将依法追究侵权者的法律责任。
<% end %>

<% content_for :content_5 do %>
    任何媒体或互联网站不得擅自转载本网站由其他单位提供的信息和服务内容，如需转载，必须与相应提供单位直接联系获得合法授权。
<% end %>

<% content_for :content_6 do %>
    本网站提供的资料如与相关纸质文本不符，以纸质文本为准；本网站提供的内容以中文版为准，英文版仅供参考。
<% end %>

app/views/static_pages/_faq_contents.en.html.erb
<% content_for :content_1 do %>
    <p><strong>What kind of organization are we?</strong></p>
    <p>
    The HanSeBridge International Chamber of Commerce was registered in Gothenburg in Sweden. It is a non-profit service organization composed of the Chinese professionals, academics, experts and overseas Chinese in Sweden.
    </p>
<% end %>

<% content_for :content_2 do %>
    <p><strong>What is the mission of Hansebridge International Chamber of Commerce?</strong></p>
    <p>
    The HanSeBridge International Chamber of Commerce is devoted to promote commercial 
    activities, offer production exhibition services, platform for investment and trade, cultural 
    communication and training between China and Sweden etc. HanSeBridge provides contacts 
    and relationship, establish investment and financing channels, offers necessary information, 
    build platform of advertising and assistance, assists communication between companies and 
    governments, shares resources and promote brands.
    </p>
<% end %>

<% content_for :content_3 do %>
    <p><strong>How to become a member of the HanSeBridge International Chamber of Commerce?</strong></p>
    <p>
    Membership enrollment process is shown in the table
    <br>
    <br>
    <%= image_tag("enroll_en.png", size: "500x600") %>
    </p>
<% end %>

<% content_for :content_4 do %>
    <p><strong>What are the benefits of being a member of the HanSeBridge International Chamber of Commerce?</strong></p>
    <p>
    <ul>
        <li>
            Members can expand social contacts, meet experts from the same industry and various industries, and senior government or company officials, build personal network, to set the foundation for finding a suitable job, and indicate the direction of future career development.
        </li>
        <li>
            With the aid of this platform, members can reflect personal professional advantage, market themselves and achieve self-worth,  turn theoretical knowledge and practical experience into productivity, serve the society, improve the China-Sweden interaction, communication and development. 
        </li>
        <li>
            Anyone that made  important contribution to the  HanSeBridge International Chamber of Commerce, or  any domestic and foreign institutions, experts and scholars that have reputations, can be granted honorary members or honorary body corporate members by meeting organized by the chairman (as discussed and adopted by the steering committee meeting).
        </li>
    </ul>
    </p>
<% end %>

<% content_for :content_5 do %>
    <p><strong>Any other questions, please contact the Department of General Affairs.
        <a href="mailto:info@hansebridge.org">info@hansebridge.org</a>
    </strong></p>
<% end %>

app/views/static_pages/activities.html.erb
<% provide(:title, t("Activities")) %>

app/views/users/index.html.erb
<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="page-header text-center">
            <h1><i class="fa fa-user fa-1g icon_color"></i> <span class="golden"> <%= t('Users')%></span> </h1>
        </div>

        <div class="col-sm-10 col-sm-offset-1">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th><%= t('Email') %></th>
                        <th><%= t('Created at') %></th>
                        <th><%= t('Updated at') %></th>
                        <th><%= t('Actions') %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                        <tr>
                            <td> <%= user.email %></td>
                            <td> <%= user.created_at %></td>
                            <td> <%= user.updated_at %></td>
                            <td><%= link_to t('Show'), user, :class => 'btn btn-mini btn-primary' %></td>
                            <td><%= link_to t('Edit'), edit_user_path(user),  :class => 'btn btn-mini btn-success'%></td>
                            <td>
                                <%= link_to t('Delete'), user, :method => :delete, data: {confirm: t("Are you sure?")}, :class => 'btn btn-mini btn-danger' %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <%= will_paginate %>
        </div>
    </div>
</div>


<div class="divider"></div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="page-header text-center">
            <h1><i class="fa fa-user fa-1g icon_color"></i> <span class="golden"> <%= t('Profile')%></span> </h1>
        </div>

        <div class="col-sm-10 col-sm-offset-1">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th><%= t('Email') %></th>
                        <th><%= t('Created at') %></th>
                        <th><%= t('Updated at') %></th>
                        <th><%= t('Actions') %></th>
                    </tr>
                </thead>
                <tbody>
                    <td> <%= @user.email %></td>
                    <td> <%= @user.created_at %></td>
                    <td> <%= @user.updated_at %></td>
                    <td><%= link_to t('Edit'), edit_user_path(@user),  :class => 'btn btn-mini btn-success'%></td>
                    <td><%= link_to t('Delete'), @user, :method => :delete, data: {confirm: t("Are you sure?")}, :class => 'btn btn-mini btn-danger' %></td>
                </tbody>
            </table>

        </div>
    </div>
</div>


<div class="divider"></div>